/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectLookup from './ObjectLookup';
import RelationshipType from './RelationshipType';

/**
 * The ActivityFeedLookup model module.
 * @module Pipeless/model/ActivityFeedLookup
 * @version 1.0
 */
class ActivityFeedLookup {
    /**
     * Constructs a new <code>ActivityFeedLookup</code>.
     * @alias module:Pipeless/model/ActivityFeedLookup
     * @param entity {module:Pipeless/model/ObjectLookup} 
     */
    constructor(entity) { 
        
        ActivityFeedLookup.initialize(this, entity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, entity) { 
        obj['entity'] = entity;
    }

    /**
     * Constructs a <code>ActivityFeedLookup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/ActivityFeedLookup} obj Optional instance to populate.
     * @return {module:Pipeless/model/ActivityFeedLookup} The populated <code>ActivityFeedLookup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivityFeedLookup();

            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ObjectLookup.constructFromObject(data['entity']);
            }
            if (data.hasOwnProperty('relationship_types')) {
                obj['relationship_types'] = ApiClient.convertToType(data['relationship_types'], [RelationshipType]);
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectLookup} entity
 */
ActivityFeedLookup.prototype['entity'] = undefined;

/**
 * @member {Array.<module:Pipeless/model/RelationshipType>} relationship_types
 */
ActivityFeedLookup.prototype['relationship_types'] = undefined;

/**
 * @member {Number} limit
 */
ActivityFeedLookup.prototype['limit'] = undefined;

/**
 * @member {String} before
 */
ActivityFeedLookup.prototype['before'] = undefined;






export default ActivityFeedLookup;

