/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetActivityActionsFeedResultActions from './GetActivityActionsFeedResultActions';
import ObjectReadable from './ObjectReadable';

/**
 * The GetActivityActionsFeedResultEvents model module.
 * @module Pipeless/model/GetActivityActionsFeedResultEvents
 * @version 1.0
 */
class GetActivityActionsFeedResultEvents {
    /**
     * Constructs a new <code>GetActivityActionsFeedResultEvents</code>.
     * @alias module:Pipeless/model/GetActivityActionsFeedResultEvents
     * @param actionObject {module:Pipeless/model/ObjectReadable} 
     * @param actions {Array.<module:Pipeless/model/GetActivityActionsFeedResultActions>} 
     */
    constructor(actionObject, actions) { 
        
        GetActivityActionsFeedResultEvents.initialize(this, actionObject, actions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, actionObject, actions) { 
        obj['action_object'] = actionObject;
        obj['actions'] = actions;
    }

    /**
     * Constructs a <code>GetActivityActionsFeedResultEvents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/GetActivityActionsFeedResultEvents} obj Optional instance to populate.
     * @return {module:Pipeless/model/GetActivityActionsFeedResultEvents} The populated <code>GetActivityActionsFeedResultEvents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetActivityActionsFeedResultEvents();

            if (data.hasOwnProperty('action_object')) {
                obj['action_object'] = ObjectReadable.constructFromObject(data['action_object']);
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [GetActivityActionsFeedResultActions]);
            }
            if (data.hasOwnProperty('cursor')) {
                obj['cursor'] = ApiClient.convertToType(data['cursor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectReadable} action_object
 */
GetActivityActionsFeedResultEvents.prototype['action_object'] = undefined;

/**
 * @member {Array.<module:Pipeless/model/GetActivityActionsFeedResultActions>} actions
 */
GetActivityActionsFeedResultEvents.prototype['actions'] = undefined;

/**
 * @member {String} cursor
 */
GetActivityActionsFeedResultEvents.prototype['cursor'] = undefined;






export default GetActivityActionsFeedResultEvents;

