/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetActivityActionsFeedResultEvents from './GetActivityActionsFeedResultEvents';
import PageInfo from './PageInfo';

/**
 * The GetActivityActionsFeedResult model module.
 * @module Pipeless/model/GetActivityActionsFeedResult
 * @version 1.0
 */
class GetActivityActionsFeedResult {
    /**
     * Constructs a new <code>GetActivityActionsFeedResult</code>.
     * @alias module:Pipeless/model/GetActivityActionsFeedResult
     * @param events {Array.<module:Pipeless/model/GetActivityActionsFeedResultEvents>} 
     * @param pageInfo {module:Pipeless/model/PageInfo} 
     */
    constructor(events, pageInfo) { 
        
        GetActivityActionsFeedResult.initialize(this, events, pageInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, events, pageInfo) { 
        obj['events'] = events;
        obj['page_info'] = pageInfo;
    }

    /**
     * Constructs a <code>GetActivityActionsFeedResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/GetActivityActionsFeedResult} obj Optional instance to populate.
     * @return {module:Pipeless/model/GetActivityActionsFeedResult} The populated <code>GetActivityActionsFeedResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetActivityActionsFeedResult();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [GetActivityActionsFeedResultEvents]);
            }
            if (data.hasOwnProperty('page_info')) {
                obj['page_info'] = PageInfo.constructFromObject(data['page_info']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Pipeless/model/GetActivityActionsFeedResultEvents>} events
 */
GetActivityActionsFeedResult.prototype['events'] = undefined;

/**
 * @member {module:Pipeless/model/PageInfo} page_info
 */
GetActivityActionsFeedResult.prototype['page_info'] = undefined;






export default GetActivityActionsFeedResult;

