/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectReadable from './ObjectReadable';
import RelationshipReadable from './RelationshipReadable';

/**
 * The GetRecentEventsResultItemEvent model module.
 * @module Pipeless/model/GetRecentEventsResultItemEvent
 * @version 1.0
 */
class GetRecentEventsResultItemEvent {
    /**
     * Constructs a new <code>GetRecentEventsResultItemEvent</code>.
     * @alias module:Pipeless/model/GetRecentEventsResultItemEvent
     * @param startObject {module:Pipeless/model/ObjectReadable} 
     * @param relationship {module:Pipeless/model/RelationshipReadable} 
     * @param endObject {module:Pipeless/model/ObjectReadable} 
     */
    constructor(startObject, relationship, endObject) { 
        
        GetRecentEventsResultItemEvent.initialize(this, startObject, relationship, endObject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startObject, relationship, endObject) { 
        obj['start_object'] = startObject;
        obj['relationship'] = relationship;
        obj['end_object'] = endObject;
    }

    /**
     * Constructs a <code>GetRecentEventsResultItemEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/GetRecentEventsResultItemEvent} obj Optional instance to populate.
     * @return {module:Pipeless/model/GetRecentEventsResultItemEvent} The populated <code>GetRecentEventsResultItemEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecentEventsResultItemEvent();

            if (data.hasOwnProperty('start_object')) {
                obj['start_object'] = ObjectReadable.constructFromObject(data['start_object']);
            }
            if (data.hasOwnProperty('relationship')) {
                obj['relationship'] = RelationshipReadable.constructFromObject(data['relationship']);
            }
            if (data.hasOwnProperty('end_object')) {
                obj['end_object'] = ObjectReadable.constructFromObject(data['end_object']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectReadable} start_object
 */
GetRecentEventsResultItemEvent.prototype['start_object'] = undefined;

/**
 * @member {module:Pipeless/model/RelationshipReadable} relationship
 */
GetRecentEventsResultItemEvent.prototype['relationship'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectReadable} end_object
 */
GetRecentEventsResultItemEvent.prototype['end_object'] = undefined;






export default GetRecentEventsResultItemEvent;

