/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetRecentEventsResultItemEvent from './GetRecentEventsResultItemEvent';

/**
 * The GetRecentEventsResultItem model module.
 * @module Pipeless/model/GetRecentEventsResultItem
 * @version 1.0
 */
class GetRecentEventsResultItem {
    /**
     * Constructs a new <code>GetRecentEventsResultItem</code>.
     * @alias module:Pipeless/model/GetRecentEventsResultItem
     * @param eventAt {Date} 
     * @param event {module:Pipeless/model/GetRecentEventsResultItemEvent} 
     */
    constructor(eventAt, event) { 
        
        GetRecentEventsResultItem.initialize(this, eventAt, event);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventAt, event) { 
        obj['event_at'] = eventAt;
        obj['event'] = event;
    }

    /**
     * Constructs a <code>GetRecentEventsResultItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/GetRecentEventsResultItem} obj Optional instance to populate.
     * @return {module:Pipeless/model/GetRecentEventsResultItem} The populated <code>GetRecentEventsResultItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecentEventsResultItem();

            if (data.hasOwnProperty('event_at')) {
                obj['event_at'] = ApiClient.convertToType(data['event_at'], 'Date');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = GetRecentEventsResultItemEvent.constructFromObject(data['event']);
            }
        }
        return obj;
    }


}

/**
 * @member {Date} event_at
 */
GetRecentEventsResultItem.prototype['event_at'] = undefined;

/**
 * @member {module:Pipeless/model/GetRecentEventsResultItemEvent} event
 */
GetRecentEventsResultItem.prototype['event'] = undefined;






export default GetRecentEventsResultItem;

