/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The InlineObject9 model module.
 * @module Pipeless/model/InlineObject9
 * @version 1.0
 */
class InlineObject9 {
    /**
     * Constructs a new <code>InlineObject9</code>.
     * @alias module:Pipeless/model/InlineObject9
     * @param objectType {module:Pipeless/model/ObjectType} 
     */
    constructor(objectType) { 
        
        InlineObject9.initialize(this, objectType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objectType) { 
        obj['object_type'] = objectType;
    }

    /**
     * Constructs a <code>InlineObject9</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject9} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject9} The populated <code>InlineObject9</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject9();

            if (data.hasOwnProperty('object_type')) {
                obj['object_type'] = ObjectType.constructFromObject(data['object_type']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectType} object_type
 */
InlineObject9.prototype['object_type'] = undefined;






export default InlineObject9;

