/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectLookup from './ObjectLookup';
import V1AppsAppIdObjectsNewProps from './V1AppsAppIdObjectsNewProps';

/**
 * The InlineObject5 model module.
 * @module Pipeless/model/InlineObject5
 * @version 1.0
 */
class InlineObject5 {
    /**
     * Constructs a new <code>InlineObject5</code>.
     * @alias module:Pipeless/model/InlineObject5
     * @param _object {module:Pipeless/model/ObjectLookup} 
     * @param newProps {module:Pipeless/model/V1AppsAppIdObjectsNewProps} 
     */
    constructor(_object, newProps) { 
        
        InlineObject5.initialize(this, _object, newProps);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _object, newProps) { 
        obj['object'] = _object;
        obj['new_props'] = newProps;
    }

    /**
     * Constructs a <code>InlineObject5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject5} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject5} The populated <code>InlineObject5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject5();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ObjectLookup.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('new_props')) {
                obj['new_props'] = V1AppsAppIdObjectsNewProps.constructFromObject(data['new_props']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectLookup} object
 */
InlineObject5.prototype['object'] = undefined;

/**
 * @member {module:Pipeless/model/V1AppsAppIdObjectsNewProps} new_props
 */
InlineObject5.prototype['new_props'] = undefined;






export default InlineObject5;

