/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AppsAppIdEventsBatchEvents from './V1AppsAppIdEventsBatchEvents';

/**
 * The InlineObject2 model module.
 * @module Pipeless/model/InlineObject2
 * @version 1.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:Pipeless/model/InlineObject2
     * @param events {Array.<module:Pipeless/model/V1AppsAppIdEventsBatchEvents>} The events to be added.
     */
    constructor(events) { 
        
        InlineObject2.initialize(this, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, events) { 
        obj['events'] = events;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject2} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [V1AppsAppIdEventsBatchEvents]);
            }
            if (data.hasOwnProperty('synchronous')) {
                obj['synchronous'] = ApiClient.convertToType(data['synchronous'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The events to be added.
 * @member {Array.<module:Pipeless/model/V1AppsAppIdEventsBatchEvents>} events
 */
InlineObject2.prototype['events'] = undefined;

/**
 * Whether the events should be created asynchronously or synchronously. Default is false (asynchronous)
 * @member {Boolean} synchronous
 * @default false
 */
InlineObject2.prototype['synchronous'] = false;






export default InlineObject2;

