/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AppsAppIdEventsEvent1 from './V1AppsAppIdEventsEvent1';

/**
 * The InlineObject1 model module.
 * @module Pipeless/model/InlineObject1
 * @version 1.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:Pipeless/model/InlineObject1
     * @param event {module:Pipeless/model/V1AppsAppIdEventsEvent1} 
     */
    constructor(event) { 
        
        InlineObject1.initialize(this, event);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, event) { 
        obj['event'] = event;
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject1} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('event')) {
                obj['event'] = V1AppsAppIdEventsEvent1.constructFromObject(data['event']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/V1AppsAppIdEventsEvent1} event
 */
InlineObject1.prototype['event'] = undefined;






export default InlineObject1;

