/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectLookup from './ObjectLookup';

/**
 * The InlineObject12 model module.
 * @module Pipeless/model/InlineObject12
 * @version 1.0
 */
class InlineObject12 {
    /**
     * Constructs a new <code>InlineObject12</code>.
     * @alias module:Pipeless/model/InlineObject12
     * @param _object {module:Pipeless/model/ObjectLookup} 
     * @param contentObjectType {module:Pipeless/model/InlineObject12.ContentObjectTypeEnum} The object type of the content associated to your tags. Ex. if the tags in your dataset are found on posts, then this value should be \"post\".
     */
    constructor(_object, contentObjectType) { 
        
        InlineObject12.initialize(this, _object, contentObjectType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _object, contentObjectType) { 
        obj['object'] = _object;
        obj['content_object_type'] = contentObjectType;
    }

    /**
     * Constructs a <code>InlineObject12</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject12} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject12} The populated <code>InlineObject12</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject12();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ObjectLookup.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('content_object_type')) {
                obj['content_object_type'] = ApiClient.convertToType(data['content_object_type'], 'String');
            }
            if (data.hasOwnProperty('content_tagged_relationship_type')) {
                obj['content_tagged_relationship_type'] = ApiClient.convertToType(data['content_tagged_relationship_type'], 'String');
            }
            if (data.hasOwnProperty('disregard_tag_ids')) {
                obj['disregard_tag_ids'] = ApiClient.convertToType(data['disregard_tag_ids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectLookup} object
 */
InlineObject12.prototype['object'] = undefined;

/**
 * The object type of the content associated to your tags. Ex. if the tags in your dataset are found on posts, then this value should be \"post\".
 * @member {module:Pipeless/model/InlineObject12.ContentObjectTypeEnum} content_object_type
 */
InlineObject12.prototype['content_object_type'] = undefined;

/**
 * The relationship type that represents content being tagged in your set. If no value is provided, this will default to taggedWith.
 * @member {module:Pipeless/model/InlineObject12.ContentTaggedRelationshipTypeEnum} content_tagged_relationship_type
 */
InlineObject12.prototype['content_tagged_relationship_type'] = undefined;

/**
 * Object ids that you want not to be included in the resulting tags (or whatever type target object is).
 * @member {Array.<String>} disregard_tag_ids
 */
InlineObject12.prototype['disregard_tag_ids'] = undefined;





/**
 * Allowed values for the <code>content_object_type</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject12['ContentObjectTypeEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user",

    /**
     * value: "product"
     * @const
     */
    "product": "product",

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "comment"
     * @const
     */
    "comment": "comment",

    /**
     * value: "article"
     * @const
     */
    "article": "article",

    /**
     * value: "post"
     * @const
     */
    "post": "post",

    /**
     * value: "video"
     * @const
     */
    "video": "video",

    /**
     * value: "content"
     * @const
     */
    "content": "content",

    /**
     * value: "tag"
     * @const
     */
    "tag": "tag",

    /**
     * value: "category"
     * @const
     */
    "category": "category",

    /**
     * value: "app"
     * @const
     */
    "app": "app",

    /**
     * value: "book"
     * @const
     */
    "book": "book",

    /**
     * value: "person"
     * @const
     */
    "person": "person",

    /**
     * value: "skill"
     * @const
     */
    "skill": "skill",

    /**
     * value: "job"
     * @const
     */
    "job": "job",

    /**
     * value: "company"
     * @const
     */
    "company": "company",

    /**
     * value: "account"
     * @const
     */
    "account": "account",

    /**
     * value: "card"
     * @const
     */
    "card": "card",

    /**
     * value: "country"
     * @const
     */
    "country": "country",

    /**
     * value: "state"
     * @const
     */
    "state": "state",

    /**
     * value: "film"
     * @const
     */
    "film": "film",

    /**
     * value: "cart"
     * @const
     */
    "cart": "cart"
};


/**
 * Allowed values for the <code>content_tagged_relationship_type</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject12['ContentTaggedRelationshipTypeEnum'] = {

    /**
     * value: "posted"
     * @const
     */
    "posted": "posted",

    /**
     * value: "followed"
     * @const
     */
    "followed": "followed",

    /**
     * value: "liked"
     * @const
     */
    "liked": "liked",

    /**
     * value: "favorited"
     * @const
     */
    "favorited": "favorited",

    /**
     * value: "saved"
     * @const
     */
    "saved": "saved",

    /**
     * value: "disliked"
     * @const
     */
    "disliked": "disliked",

    /**
     * value: "purchased"
     * @const
     */
    "purchased": "purchased",

    /**
     * value: "commentedOn"
     * @const
     */
    "commentedOn": "commentedOn",

    /**
     * value: "created"
     * @const
     */
    "created": "created",

    /**
     * value: "viewed"
     * @const
     */
    "viewed": "viewed",

    /**
     * value: "reported"
     * @const
     */
    "reported": "reported",

    /**
     * value: "blocked"
     * @const
     */
    "blocked": "blocked",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "authored"
     * @const
     */
    "authored": "authored",

    /**
     * value: "used"
     * @const
     */
    "used": "used",

    /**
     * value: "dismissed"
     * @const
     */
    "dismissed": "dismissed",

    /**
     * value: "loggedIn"
     * @const
     */
    "loggedIn": "loggedIn",

    /**
     * value: "taggedWith"
     * @const
     */
    "taggedWith": "taggedWith",

    /**
     * value: "categorizedIn"
     * @const
     */
    "categorizedIn": "categorizedIn",

    /**
     * value: "interestedIn"
     * @const
     */
    "interestedIn": "interestedIn",

    /**
     * value: "locatedIn"
     * @const
     */
    "locatedIn": "locatedIn",

    /**
     * value: "readQuarter"
     * @const
     */
    "readQuarter": "readQuarter",

    /**
     * value: "readHalf"
     * @const
     */
    "readHalf": "readHalf",

    /**
     * value: "readAll"
     * @const
     */
    "readAll": "readAll",

    /**
     * value: "subscribedTo"
     * @const
     */
    "subscribedTo": "subscribedTo",

    /**
     * value: "subscribedFrom"
     * @const
     */
    "subscribedFrom": "subscribedFrom",

    /**
     * value: "addedTo"
     * @const
     */
    "addedTo": "addedTo",

    /**
     * value: "madeBy"
     * @const
     */
    "madeBy": "madeBy",

    /**
     * value: "pausedOn"
     * @const
     */
    "pausedOn": "pausedOn"
};



export default InlineObject12;

