/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AppsAppIdEventsEvent from './V1AppsAppIdEventsEvent';

/**
 * The InlineObject model module.
 * @module Pipeless/model/InlineObject
 * @version 1.0
 */
class InlineObject {
    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:Pipeless/model/InlineObject
     * @param event {module:Pipeless/model/V1AppsAppIdEventsEvent} 
     */
    constructor(event) { 
        
        InlineObject.initialize(this, event);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, event) { 
        obj['event'] = event;
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('event')) {
                obj['event'] = V1AppsAppIdEventsEvent.constructFromObject(data['event']);
            }
            if (data.hasOwnProperty('synchronous')) {
                obj['synchronous'] = ApiClient.convertToType(data['synchronous'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/V1AppsAppIdEventsEvent} event
 */
InlineObject.prototype['event'] = undefined;

/**
 * Whether the event should be created asynchronously or synchronously. Default is false (asynchronous). On success, async will return 202 Accepted, sync will return 201 Created.
 * @member {Boolean} synchronous
 * @default false
 */
InlineObject.prototype['synchronous'] = false;






export default InlineObject;

