/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectLookup from './ObjectLookup';

/**
 * The InlineObject7 model module.
 * @module Pipeless/model/InlineObject7
 * @version 1.0
 */
class InlineObject7 {
    /**
     * Constructs a new <code>InlineObject7</code>.
     * @alias module:Pipeless/model/InlineObject7
     * @param _object {module:Pipeless/model/ObjectLookup} 
     */
    constructor(_object) { 
        
        InlineObject7.initialize(this, _object);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _object) { 
        obj['object'] = _object;
    }

    /**
     * Constructs a <code>InlineObject7</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/InlineObject7} obj Optional instance to populate.
     * @return {module:Pipeless/model/InlineObject7} The populated <code>InlineObject7</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject7();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ObjectLookup.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('follow_relationship_types')) {
                obj['follow_relationship_types'] = ApiClient.convertToType(data['follow_relationship_types'], ['String']);
            }
            if (data.hasOwnProperty('follow_object_types')) {
                obj['follow_object_types'] = ApiClient.convertToType(data['follow_object_types'], ['String']);
            }
            if (data.hasOwnProperty('event_relationship_types')) {
                obj['event_relationship_types'] = ApiClient.convertToType(data['event_relationship_types'], ['String']);
            }
            if (data.hasOwnProperty('event_object_types')) {
                obj['event_object_types'] = ApiClient.convertToType(data['event_object_types'], ['String']);
            }
            if (data.hasOwnProperty('exclude_self_object')) {
                obj['exclude_self_object'] = ApiClient.convertToType(data['exclude_self_object'], 'Boolean');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectLookup} object
 */
InlineObject7.prototype['object'] = undefined;

/**
 * An array of the relationship types that represent the concept of \"following\" in your data. If none provided, by default the relationship type \"followed\" will be used.
 * @member {Array.<module:Pipeless/model/InlineObject7.FollowRelationshipTypesEnum>} follow_relationship_types
 */
InlineObject7.prototype['follow_relationship_types'] = undefined;

/**
 * An array of the object types that can be followed in your dataset and that you want to be used for this activity feed. If none provided, by default any object type that is found based on the allowed follow_relationship_types will be used.
 * @member {Array.<module:Pipeless/model/InlineObject7.FollowObjectTypesEnum>} follow_object_types
 */
InlineObject7.prototype['follow_object_types'] = undefined;

/**
 * An array of the relationship types of the actions you want to show up in the activity feed. If none provided, by default any relationships that are present in the resulting feed items will be returned.
 * @member {Array.<module:Pipeless/model/InlineObject7.EventRelationshipTypesEnum>} event_relationship_types
 */
InlineObject7.prototype['event_relationship_types'] = undefined;

/**
 * An array of the object types that can appear as content in the feed. If none provided, any object type that results from the other settings will be shown in the feed.
 * @member {Array.<module:Pipeless/model/InlineObject7.EventObjectTypesEnum>} event_object_types
 */
InlineObject7.prototype['event_object_types'] = undefined;

/**
 * If this value is false (the default), then the user you are fetching the feed for can appear in the feed results as an acting user (if the user follows themself) or action user (object that is being acted on by users the user follows). If set to true, the user the feed is being fetched for will not appear in the results.
 * @member {Boolean} exclude_self_object
 */
InlineObject7.prototype['exclude_self_object'] = undefined;

/**
 * @member {Number} limit
 */
InlineObject7.prototype['limit'] = undefined;

/**
 * @member {String} before
 */
InlineObject7.prototype['before'] = undefined;





/**
 * Allowed values for the <code>followRelationshipTypes</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject7['FollowRelationshipTypesEnum'] = {

    /**
     * value: "posted"
     * @const
     */
    "posted": "posted",

    /**
     * value: "followed"
     * @const
     */
    "followed": "followed",

    /**
     * value: "liked"
     * @const
     */
    "liked": "liked",

    /**
     * value: "favorited"
     * @const
     */
    "favorited": "favorited",

    /**
     * value: "saved"
     * @const
     */
    "saved": "saved",

    /**
     * value: "disliked"
     * @const
     */
    "disliked": "disliked",

    /**
     * value: "purchased"
     * @const
     */
    "purchased": "purchased",

    /**
     * value: "commentedOn"
     * @const
     */
    "commentedOn": "commentedOn",

    /**
     * value: "created"
     * @const
     */
    "created": "created",

    /**
     * value: "viewed"
     * @const
     */
    "viewed": "viewed",

    /**
     * value: "reported"
     * @const
     */
    "reported": "reported",

    /**
     * value: "blocked"
     * @const
     */
    "blocked": "blocked",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "authored"
     * @const
     */
    "authored": "authored",

    /**
     * value: "used"
     * @const
     */
    "used": "used",

    /**
     * value: "dismissed"
     * @const
     */
    "dismissed": "dismissed",

    /**
     * value: "loggedIn"
     * @const
     */
    "loggedIn": "loggedIn",

    /**
     * value: "taggedWith"
     * @const
     */
    "taggedWith": "taggedWith",

    /**
     * value: "categorizedIn"
     * @const
     */
    "categorizedIn": "categorizedIn",

    /**
     * value: "interestedIn"
     * @const
     */
    "interestedIn": "interestedIn",

    /**
     * value: "locatedIn"
     * @const
     */
    "locatedIn": "locatedIn",

    /**
     * value: "readQuarter"
     * @const
     */
    "readQuarter": "readQuarter",

    /**
     * value: "readHalf"
     * @const
     */
    "readHalf": "readHalf",

    /**
     * value: "readAll"
     * @const
     */
    "readAll": "readAll",

    /**
     * value: "subscribedTo"
     * @const
     */
    "subscribedTo": "subscribedTo",

    /**
     * value: "subscribedFrom"
     * @const
     */
    "subscribedFrom": "subscribedFrom",

    /**
     * value: "addedTo"
     * @const
     */
    "addedTo": "addedTo",

    /**
     * value: "madeBy"
     * @const
     */
    "madeBy": "madeBy",

    /**
     * value: "pausedOn"
     * @const
     */
    "pausedOn": "pausedOn"
};


/**
 * Allowed values for the <code>followObjectTypes</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject7['FollowObjectTypesEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user",

    /**
     * value: "product"
     * @const
     */
    "product": "product",

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "comment"
     * @const
     */
    "comment": "comment",

    /**
     * value: "article"
     * @const
     */
    "article": "article",

    /**
     * value: "post"
     * @const
     */
    "post": "post",

    /**
     * value: "video"
     * @const
     */
    "video": "video",

    /**
     * value: "content"
     * @const
     */
    "content": "content",

    /**
     * value: "tag"
     * @const
     */
    "tag": "tag",

    /**
     * value: "category"
     * @const
     */
    "category": "category",

    /**
     * value: "app"
     * @const
     */
    "app": "app",

    /**
     * value: "book"
     * @const
     */
    "book": "book",

    /**
     * value: "person"
     * @const
     */
    "person": "person",

    /**
     * value: "skill"
     * @const
     */
    "skill": "skill",

    /**
     * value: "job"
     * @const
     */
    "job": "job",

    /**
     * value: "company"
     * @const
     */
    "company": "company",

    /**
     * value: "account"
     * @const
     */
    "account": "account",

    /**
     * value: "card"
     * @const
     */
    "card": "card",

    /**
     * value: "country"
     * @const
     */
    "country": "country",

    /**
     * value: "state"
     * @const
     */
    "state": "state",

    /**
     * value: "film"
     * @const
     */
    "film": "film",

    /**
     * value: "cart"
     * @const
     */
    "cart": "cart"
};


/**
 * Allowed values for the <code>eventRelationshipTypes</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject7['EventRelationshipTypesEnum'] = {

    /**
     * value: "posted"
     * @const
     */
    "posted": "posted",

    /**
     * value: "followed"
     * @const
     */
    "followed": "followed",

    /**
     * value: "liked"
     * @const
     */
    "liked": "liked",

    /**
     * value: "favorited"
     * @const
     */
    "favorited": "favorited",

    /**
     * value: "saved"
     * @const
     */
    "saved": "saved",

    /**
     * value: "disliked"
     * @const
     */
    "disliked": "disliked",

    /**
     * value: "purchased"
     * @const
     */
    "purchased": "purchased",

    /**
     * value: "commentedOn"
     * @const
     */
    "commentedOn": "commentedOn",

    /**
     * value: "created"
     * @const
     */
    "created": "created",

    /**
     * value: "viewed"
     * @const
     */
    "viewed": "viewed",

    /**
     * value: "reported"
     * @const
     */
    "reported": "reported",

    /**
     * value: "blocked"
     * @const
     */
    "blocked": "blocked",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "authored"
     * @const
     */
    "authored": "authored",

    /**
     * value: "used"
     * @const
     */
    "used": "used",

    /**
     * value: "dismissed"
     * @const
     */
    "dismissed": "dismissed",

    /**
     * value: "loggedIn"
     * @const
     */
    "loggedIn": "loggedIn",

    /**
     * value: "taggedWith"
     * @const
     */
    "taggedWith": "taggedWith",

    /**
     * value: "categorizedIn"
     * @const
     */
    "categorizedIn": "categorizedIn",

    /**
     * value: "interestedIn"
     * @const
     */
    "interestedIn": "interestedIn",

    /**
     * value: "locatedIn"
     * @const
     */
    "locatedIn": "locatedIn",

    /**
     * value: "readQuarter"
     * @const
     */
    "readQuarter": "readQuarter",

    /**
     * value: "readHalf"
     * @const
     */
    "readHalf": "readHalf",

    /**
     * value: "readAll"
     * @const
     */
    "readAll": "readAll",

    /**
     * value: "subscribedTo"
     * @const
     */
    "subscribedTo": "subscribedTo",

    /**
     * value: "subscribedFrom"
     * @const
     */
    "subscribedFrom": "subscribedFrom",

    /**
     * value: "addedTo"
     * @const
     */
    "addedTo": "addedTo",

    /**
     * value: "madeBy"
     * @const
     */
    "madeBy": "madeBy",

    /**
     * value: "pausedOn"
     * @const
     */
    "pausedOn": "pausedOn"
};


/**
 * Allowed values for the <code>eventObjectTypes</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject7['EventObjectTypesEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user",

    /**
     * value: "product"
     * @const
     */
    "product": "product",

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "comment"
     * @const
     */
    "comment": "comment",

    /**
     * value: "article"
     * @const
     */
    "article": "article",

    /**
     * value: "post"
     * @const
     */
    "post": "post",

    /**
     * value: "video"
     * @const
     */
    "video": "video",

    /**
     * value: "content"
     * @const
     */
    "content": "content",

    /**
     * value: "tag"
     * @const
     */
    "tag": "tag",

    /**
     * value: "category"
     * @const
     */
    "category": "category",

    /**
     * value: "app"
     * @const
     */
    "app": "app",

    /**
     * value: "book"
     * @const
     */
    "book": "book",

    /**
     * value: "person"
     * @const
     */
    "person": "person",

    /**
     * value: "skill"
     * @const
     */
    "skill": "skill",

    /**
     * value: "job"
     * @const
     */
    "job": "job",

    /**
     * value: "company"
     * @const
     */
    "company": "company",

    /**
     * value: "account"
     * @const
     */
    "account": "account",

    /**
     * value: "card"
     * @const
     */
    "card": "card",

    /**
     * value: "country"
     * @const
     */
    "country": "country",

    /**
     * value: "state"
     * @const
     */
    "state": "state",

    /**
     * value: "film"
     * @const
     */
    "film": "film",

    /**
     * value: "cart"
     * @const
     */
    "cart": "cart"
};



export default InlineObject7;

