/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The ObjectLookup model module.
 * @module Pipeless/model/ObjectLookup
 * @version 1.0
 */
class ObjectLookup {
    /**
     * Constructs a new <code>ObjectLookup</code>.
     * @alias module:Pipeless/model/ObjectLookup
     * @param id {String} 
     * @param type {module:Pipeless/model/ObjectType} 
     */
    constructor(id, type) { 
        
        ObjectLookup.initialize(this, id, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, type) { 
        obj['id'] = id;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ObjectLookup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/ObjectLookup} obj Optional instance to populate.
     * @return {module:Pipeless/model/ObjectLookup} The populated <code>ObjectLookup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectLookup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ObjectLookup.prototype['id'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectType} type
 */
ObjectLookup.prototype['type'] = undefined;






export default ObjectLookup;

