/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ObjectType.
* @enum {}
* @readonly
*/
export default class ObjectType {
    
        /**
         * value: "user"
         * @const
         */
        "user" = "user";

    
        /**
         * value: "product"
         * @const
         */
        "product" = "product";

    
        /**
         * value: "image"
         * @const
         */
        "image" = "image";

    
        /**
         * value: "comment"
         * @const
         */
        "comment" = "comment";

    
        /**
         * value: "article"
         * @const
         */
        "article" = "article";

    
        /**
         * value: "post"
         * @const
         */
        "post" = "post";

    
        /**
         * value: "video"
         * @const
         */
        "video" = "video";

    
        /**
         * value: "content"
         * @const
         */
        "content" = "content";

    
        /**
         * value: "tag"
         * @const
         */
        "tag" = "tag";

    
        /**
         * value: "category"
         * @const
         */
        "category" = "category";

    
        /**
         * value: "app"
         * @const
         */
        "app" = "app";

    
        /**
         * value: "book"
         * @const
         */
        "book" = "book";

    
        /**
         * value: "person"
         * @const
         */
        "person" = "person";

    
        /**
         * value: "skill"
         * @const
         */
        "skill" = "skill";

    
        /**
         * value: "job"
         * @const
         */
        "job" = "job";

    
        /**
         * value: "company"
         * @const
         */
        "company" = "company";

    
        /**
         * value: "account"
         * @const
         */
        "account" = "account";

    
        /**
         * value: "card"
         * @const
         */
        "card" = "card";

    
        /**
         * value: "country"
         * @const
         */
        "country" = "country";

    
        /**
         * value: "state"
         * @const
         */
        "state" = "state";

    
        /**
         * value: "film"
         * @const
         */
        "film" = "film";

    
        /**
         * value: "cart"
         * @const
         */
        "cart" = "cart";

    

    /**
    * Returns a <code>ObjectType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Pipeless/model/ObjectType} The enum <code>ObjectType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

