/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The ObjectWildcardLookup model module.
 * @module Pipeless/model/ObjectWildcardLookup
 * @version 1.0
 */
class ObjectWildcardLookup {
    /**
     * Constructs a new <code>ObjectWildcardLookup</code>.
     * @alias module:Pipeless/model/ObjectWildcardLookup
     * @param type {module:Pipeless/model/ObjectType} 
     */
    constructor(type) { 
        
        ObjectWildcardLookup.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ObjectWildcardLookup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/ObjectWildcardLookup} obj Optional instance to populate.
     * @return {module:Pipeless/model/ObjectWildcardLookup} The populated <code>ObjectWildcardLookup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectWildcardLookup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('all')) {
                obj['all'] = ApiClient.convertToType(data['all'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ObjectWildcardLookup.prototype['id'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectType} type
 */
ObjectWildcardLookup.prototype['type'] = undefined;

/**
 * If you want to delete all the relationships from the start object to the specified end object type (of any id), set this value to true. If true, the end object of the event will match any object of the specified type. Default value is false, meaning a specific id is required.
 * @member {Boolean} all
 */
ObjectWildcardLookup.prototype['all'] = undefined;






export default ObjectWildcardLookup;

