/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The ObjectReadable model module.
 * @module Pipeless/model/ObjectReadable
 * @version 1.0
 */
class ObjectReadable {
    /**
     * Constructs a new <code>ObjectReadable</code>.
     * @alias module:Pipeless/model/ObjectReadable
     * @param id {String} 
     * @param type {module:Pipeless/model/ObjectType} 
     * @param createdOn {Date} 
     * @param modifiedOn {Date} 
     */
    constructor(id, type, createdOn, modifiedOn) { 
        
        ObjectReadable.initialize(this, id, type, createdOn, modifiedOn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, type, createdOn, modifiedOn) { 
        obj['id'] = id;
        obj['type'] = type;
        obj['created_on'] = createdOn;
        obj['modified_on'] = modifiedOn;
    }

    /**
     * Constructs a <code>ObjectReadable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/ObjectReadable} obj Optional instance to populate.
     * @return {module:Pipeless/model/ObjectReadable} The populated <code>ObjectReadable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectReadable();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'Date');
            }
            if (data.hasOwnProperty('modified_on')) {
                obj['modified_on'] = ApiClient.convertToType(data['modified_on'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ObjectReadable.prototype['id'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectType} type
 */
ObjectReadable.prototype['type'] = undefined;

/**
 * @member {Date} created_on
 */
ObjectReadable.prototype['created_on'] = undefined;

/**
 * @member {Date} modified_on
 */
ObjectReadable.prototype['modified_on'] = undefined;






export default ObjectReadable;

