/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageInfo model module.
 * @module Pipeless/model/PageInfo
 * @version 1.0
 */
class PageInfo {
    /**
     * Constructs a new <code>PageInfo</code>.
     * @alias module:Pipeless/model/PageInfo
     * @param endCursor {String} 
     * @param hasNextPage {Boolean} 
     */
    constructor(endCursor, hasNextPage) { 
        
        PageInfo.initialize(this, endCursor, hasNextPage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, endCursor, hasNextPage) { 
        obj['end_cursor'] = endCursor;
        obj['has_next_page'] = hasNextPage;
    }

    /**
     * Constructs a <code>PageInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/PageInfo} obj Optional instance to populate.
     * @return {module:Pipeless/model/PageInfo} The populated <code>PageInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageInfo();

            if (data.hasOwnProperty('end_cursor')) {
                obj['end_cursor'] = ApiClient.convertToType(data['end_cursor'], 'String');
            }
            if (data.hasOwnProperty('has_next_page')) {
                obj['has_next_page'] = ApiClient.convertToType(data['has_next_page'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} end_cursor
 */
PageInfo.prototype['end_cursor'] = undefined;

/**
 * @member {Boolean} has_next_page
 */
PageInfo.prototype['has_next_page'] = undefined;






export default PageInfo;

