/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectReadable from './ObjectReadable';

/**
 * The RecommendationsResultItems model module.
 * @module Pipeless/model/RecommendationsResultItems
 * @version 1.0
 */
class RecommendationsResultItems {
    /**
     * Constructs a new <code>RecommendationsResultItems</code>.
     * @alias module:Pipeless/model/RecommendationsResultItems
     * @param _object {module:Pipeless/model/ObjectReadable} 
     */
    constructor(_object) { 
        
        RecommendationsResultItems.initialize(this, _object);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _object) { 
        obj['object'] = _object;
    }

    /**
     * Constructs a <code>RecommendationsResultItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/RecommendationsResultItems} obj Optional instance to populate.
     * @return {module:Pipeless/model/RecommendationsResultItems} The populated <code>RecommendationsResultItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecommendationsResultItems();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ObjectReadable.constructFromObject(data['object']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectReadable} object
 */
RecommendationsResultItems.prototype['object'] = undefined;






export default RecommendationsResultItems;

