/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecommendationsResultItems from './RecommendationsResultItems';

/**
 * The RecommendationsResult model module.
 * @module Pipeless/model/RecommendationsResult
 * @version 1.0
 */
class RecommendationsResult {
    /**
     * Constructs a new <code>RecommendationsResult</code>.
     * @alias module:Pipeless/model/RecommendationsResult
     * @param items {Array.<module:Pipeless/model/RecommendationsResultItems>} 
     */
    constructor(items) { 
        
        RecommendationsResult.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>RecommendationsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/RecommendationsResult} obj Optional instance to populate.
     * @return {module:Pipeless/model/RecommendationsResult} The populated <code>RecommendationsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecommendationsResult();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [RecommendationsResultItems]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Pipeless/model/RecommendationsResultItems>} items
 */
RecommendationsResult.prototype['items'] = undefined;






export default RecommendationsResult;

