/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The RelationshipCountsResultStats model module.
 * @module Pipeless/model/RelationshipCountsResultStats
 * @version 1.0
 */
class RelationshipCountsResultStats {
    /**
     * Constructs a new <code>RelationshipCountsResultStats</code>.
     * @alias module:Pipeless/model/RelationshipCountsResultStats
     * @param type {module:Pipeless/model/ObjectType} 
     * @param direction {module:Pipeless/model/RelationshipCountsResultStats.DirectionEnum} 
     * @param otherObjectType {module:Pipeless/model/ObjectType} 
     * @param count {Number} 
     */
    constructor(type, direction, otherObjectType, count) { 
        
        RelationshipCountsResultStats.initialize(this, type, direction, otherObjectType, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, direction, otherObjectType, count) { 
        obj['type'] = type;
        obj['direction'] = direction;
        obj['other_object_type'] = otherObjectType;
        obj['count'] = count;
    }

    /**
     * Constructs a <code>RelationshipCountsResultStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/RelationshipCountsResultStats} obj Optional instance to populate.
     * @return {module:Pipeless/model/RelationshipCountsResultStats} The populated <code>RelationshipCountsResultStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelationshipCountsResultStats();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('other_object_type')) {
                obj['other_object_type'] = ObjectType.constructFromObject(data['other_object_type']);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectType} type
 */
RelationshipCountsResultStats.prototype['type'] = undefined;

/**
 * @member {module:Pipeless/model/RelationshipCountsResultStats.DirectionEnum} direction
 */
RelationshipCountsResultStats.prototype['direction'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectType} other_object_type
 */
RelationshipCountsResultStats.prototype['other_object_type'] = undefined;

/**
 * @member {Number} count
 */
RelationshipCountsResultStats.prototype['count'] = undefined;





/**
 * Allowed values for the <code>direction</code> property.
 * @enum {String}
 * @readonly
 */
RelationshipCountsResultStats['DirectionEnum'] = {

    /**
     * value: "incoming"
     * @const
     */
    "incoming": "incoming",

    /**
     * value: "outgoing"
     * @const
     */
    "outgoing": "outgoing"
};



export default RelationshipCountsResultStats;

