/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class RelationshipType.
* @enum {}
* @readonly
*/
export default class RelationshipType {
    
        /**
         * value: "posted"
         * @const
         */
        "posted" = "posted";

    
        /**
         * value: "followed"
         * @const
         */
        "followed" = "followed";

    
        /**
         * value: "liked"
         * @const
         */
        "liked" = "liked";

    
        /**
         * value: "favorited"
         * @const
         */
        "favorited" = "favorited";

    
        /**
         * value: "saved"
         * @const
         */
        "saved" = "saved";

    
        /**
         * value: "disliked"
         * @const
         */
        "disliked" = "disliked";

    
        /**
         * value: "purchased"
         * @const
         */
        "purchased" = "purchased";

    
        /**
         * value: "commentedOn"
         * @const
         */
        "commentedOn" = "commentedOn";

    
        /**
         * value: "created"
         * @const
         */
        "created" = "created";

    
        /**
         * value: "viewed"
         * @const
         */
        "viewed" = "viewed";

    
        /**
         * value: "reported"
         * @const
         */
        "reported" = "reported";

    
        /**
         * value: "blocked"
         * @const
         */
        "blocked" = "blocked";

    
        /**
         * value: "deleted"
         * @const
         */
        "deleted" = "deleted";

    
        /**
         * value: "authored"
         * @const
         */
        "authored" = "authored";

    
        /**
         * value: "used"
         * @const
         */
        "used" = "used";

    
        /**
         * value: "dismissed"
         * @const
         */
        "dismissed" = "dismissed";

    
        /**
         * value: "loggedIn"
         * @const
         */
        "loggedIn" = "loggedIn";

    
        /**
         * value: "taggedWith"
         * @const
         */
        "taggedWith" = "taggedWith";

    
        /**
         * value: "categorizedIn"
         * @const
         */
        "categorizedIn" = "categorizedIn";

    
        /**
         * value: "interestedIn"
         * @const
         */
        "interestedIn" = "interestedIn";

    
        /**
         * value: "locatedIn"
         * @const
         */
        "locatedIn" = "locatedIn";

    
        /**
         * value: "readQuarter"
         * @const
         */
        "readQuarter" = "readQuarter";

    
        /**
         * value: "readHalf"
         * @const
         */
        "readHalf" = "readHalf";

    
        /**
         * value: "readAll"
         * @const
         */
        "readAll" = "readAll";

    
        /**
         * value: "subscribedTo"
         * @const
         */
        "subscribedTo" = "subscribedTo";

    
        /**
         * value: "subscribedFrom"
         * @const
         */
        "subscribedFrom" = "subscribedFrom";

    
        /**
         * value: "addedTo"
         * @const
         */
        "addedTo" = "addedTo";

    
        /**
         * value: "madeBy"
         * @const
         */
        "madeBy" = "madeBy";

    
        /**
         * value: "pausedOn"
         * @const
         */
        "pausedOn" = "pausedOn";

    

    /**
    * Returns a <code>RelationshipType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Pipeless/model/RelationshipType} The enum <code>RelationshipType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

