/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelationshipType from './RelationshipType';

/**
 * The RelationshipReadable model module.
 * @module Pipeless/model/RelationshipReadable
 * @version 1.0
 */
class RelationshipReadable {
    /**
     * Constructs a new <code>RelationshipReadable</code>.
     * @alias module:Pipeless/model/RelationshipReadable
     * @param type {module:Pipeless/model/RelationshipType} 
     * @param createdOn {Date} 
     */
    constructor(type, createdOn) { 
        
        RelationshipReadable.initialize(this, type, createdOn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, createdOn) { 
        obj['type'] = type;
        obj['created_on'] = createdOn;
    }

    /**
     * Constructs a <code>RelationshipReadable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/RelationshipReadable} obj Optional instance to populate.
     * @return {module:Pipeless/model/RelationshipReadable} The populated <code>RelationshipReadable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelationshipReadable();

            if (data.hasOwnProperty('type')) {
                obj['type'] = RelationshipType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/RelationshipType} type
 */
RelationshipReadable.prototype['type'] = undefined;

/**
 * @member {Date} created_on
 */
RelationshipReadable.prototype['created_on'] = undefined;






export default RelationshipReadable;

