/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectWriteable from './ObjectWriteable';
import RelationshipWriteable from './RelationshipWriteable';

/**
 * The V1AppsAppIdEventsEvent model module.
 * @module Pipeless/model/V1AppsAppIdEventsEvent
 * @version 1.0
 */
class V1AppsAppIdEventsEvent {
    /**
     * Constructs a new <code>V1AppsAppIdEventsEvent</code>.
     * The event to be added.
     * @alias module:Pipeless/model/V1AppsAppIdEventsEvent
     * @param startObject {module:Pipeless/model/ObjectWriteable} 
     * @param relationship {module:Pipeless/model/RelationshipWriteable} 
     * @param endObject {module:Pipeless/model/ObjectWriteable} 
     */
    constructor(startObject, relationship, endObject) { 
        
        V1AppsAppIdEventsEvent.initialize(this, startObject, relationship, endObject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startObject, relationship, endObject) { 
        obj['start_object'] = startObject;
        obj['relationship'] = relationship;
        obj['end_object'] = endObject;
    }

    /**
     * Constructs a <code>V1AppsAppIdEventsEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/V1AppsAppIdEventsEvent} obj Optional instance to populate.
     * @return {module:Pipeless/model/V1AppsAppIdEventsEvent} The populated <code>V1AppsAppIdEventsEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AppsAppIdEventsEvent();

            if (data.hasOwnProperty('start_object')) {
                obj['start_object'] = ObjectWriteable.constructFromObject(data['start_object']);
            }
            if (data.hasOwnProperty('relationship')) {
                obj['relationship'] = RelationshipWriteable.constructFromObject(data['relationship']);
            }
            if (data.hasOwnProperty('end_object')) {
                obj['end_object'] = ObjectWriteable.constructFromObject(data['end_object']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectWriteable} start_object
 */
V1AppsAppIdEventsEvent.prototype['start_object'] = undefined;

/**
 * @member {module:Pipeless/model/RelationshipWriteable} relationship
 */
V1AppsAppIdEventsEvent.prototype['relationship'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectWriteable} end_object
 */
V1AppsAppIdEventsEvent.prototype['end_object'] = undefined;






export default V1AppsAppIdEventsEvent;

