/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1AppsAppIdObjectsNewProps model module.
 * @module Pipeless/model/V1AppsAppIdObjectsNewProps
 * @version 1.0
 */
class V1AppsAppIdObjectsNewProps {
    /**
     * Constructs a new <code>V1AppsAppIdObjectsNewProps</code>.
     * New properties to be set for the object.
     * @alias module:Pipeless/model/V1AppsAppIdObjectsNewProps
     */
    constructor() { 
        
        V1AppsAppIdObjectsNewProps.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AppsAppIdObjectsNewProps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/V1AppsAppIdObjectsNewProps} obj Optional instance to populate.
     * @return {module:Pipeless/model/V1AppsAppIdObjectsNewProps} The populated <code>V1AppsAppIdObjectsNewProps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AppsAppIdObjectsNewProps();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'Date');
            }
            if (data.hasOwnProperty('modified_on')) {
                obj['modified_on'] = ApiClient.convertToType(data['modified_on'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
V1AppsAppIdObjectsNewProps.prototype['id'] = undefined;

/**
 * New created_on (in datetime format) for the object. If not included, the current value will be kept.
 * @member {Date} created_on
 */
V1AppsAppIdObjectsNewProps.prototype['created_on'] = undefined;

/**
 * New modified_on (in datetime format) for the object. If not included, the current value will be kept.
 * @member {Date} modified_on
 */
V1AppsAppIdObjectsNewProps.prototype['modified_on'] = undefined;






export default V1AppsAppIdObjectsNewProps;

