/**
 * Pipeless
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectLookup from './ObjectLookup';
import ObjectWildcardLookup from './ObjectWildcardLookup';
import V1AppsAppIdEventsEvent1Relationship from './V1AppsAppIdEventsEvent1Relationship';

/**
 * The V1AppsAppIdEventsEvent1 model module.
 * @module Pipeless/model/V1AppsAppIdEventsEvent1
 * @version 1.0
 */
class V1AppsAppIdEventsEvent1 {
    /**
     * Constructs a new <code>V1AppsAppIdEventsEvent1</code>.
     * Details to specify which event(s) should be deleted. Only events that match all 3 event parts (start, relationship, end) will be deleted.
     * @alias module:Pipeless/model/V1AppsAppIdEventsEvent1
     * @param startObject {module:Pipeless/model/ObjectLookup} 
     * @param relationship {module:Pipeless/model/V1AppsAppIdEventsEvent1Relationship} 
     * @param endObject {module:Pipeless/model/ObjectWildcardLookup} 
     */
    constructor(startObject, relationship, endObject) { 
        
        V1AppsAppIdEventsEvent1.initialize(this, startObject, relationship, endObject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startObject, relationship, endObject) { 
        obj['start_object'] = startObject;
        obj['relationship'] = relationship;
        obj['end_object'] = endObject;
    }

    /**
     * Constructs a <code>V1AppsAppIdEventsEvent1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Pipeless/model/V1AppsAppIdEventsEvent1} obj Optional instance to populate.
     * @return {module:Pipeless/model/V1AppsAppIdEventsEvent1} The populated <code>V1AppsAppIdEventsEvent1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AppsAppIdEventsEvent1();

            if (data.hasOwnProperty('start_object')) {
                obj['start_object'] = ObjectLookup.constructFromObject(data['start_object']);
            }
            if (data.hasOwnProperty('relationship')) {
                obj['relationship'] = V1AppsAppIdEventsEvent1Relationship.constructFromObject(data['relationship']);
            }
            if (data.hasOwnProperty('end_object')) {
                obj['end_object'] = ObjectWildcardLookup.constructFromObject(data['end_object']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Pipeless/model/ObjectLookup} start_object
 */
V1AppsAppIdEventsEvent1.prototype['start_object'] = undefined;

/**
 * @member {module:Pipeless/model/V1AppsAppIdEventsEvent1Relationship} relationship
 */
V1AppsAppIdEventsEvent1.prototype['relationship'] = undefined;

/**
 * @member {module:Pipeless/model/ObjectWildcardLookup} end_object
 */
V1AppsAppIdEventsEvent1.prototype['end_object'] = undefined;






export default V1AppsAppIdEventsEvent1;

